apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-demo
  namespace: demo
spec:
  ingressClassName: traefik
  tls:
    - hosts:
      - demo.local
      secretName: demo-tls
  rules:
    - host: demo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: node-demo
                port:
                  number: 80